server:
  port: 8083 # New Port!

spring:
  application:
    name: interaction-service
  datasource:
    hikari:
      maximum-pool-size: 3  # Reduces the "footprint" of each microservice
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.qhemejaizwfsdchbjitp
    password: EEYZoX0Zne7bDclG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/