server:
  port: 8083 # New Port!

spring:
  application:
    name: interaction-service
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: streamix


eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@localhost:8761/eureka/