server:
  port: 8081

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
    username: postgres.qhemejaizwfsdchbjitp
    password: ${SUPABASE_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Crucial: This creates the tables for you automatically!
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # Google Gmail API Configuration
  gmail:
    client-id: ${GMAIL_CLIENT_ID}
    client-secret: ${GMAIL_CLIENT_SECRET}
    refresh-token: ${GMAIL_REFRESH_TOKEN}
    from-email: veloxproject.dm@gmail.com

  data:
    redis:
      host: advanced-squid-31813.upstash.io
      port: 6379
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
jwt:
  secret: ${JWT_SECRET}
eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
      