spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route for Identity Service (Index 0)
        - id: identity-service
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/auth/**

        # Route for Catalog Service (Index 1)
        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/movie/**

        # Route for Interaction Service (Index 2)
        - id: interaction-service
          uri: lb://INTERACTION-SERVICE
          predicates:
            - Path=/interaction/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/