spring:
  application:
    name: catalog-service
  mongodb:
    uri: ${MONGODB_URI}

server:
  port: 8082

tmdb:
  api:
    key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_USERNAME:admin}:${EUREKA_PASSWORD:admin}@${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/
