spring:
  application:
    name: catalog-service
  mongodb:
    uri: mongodb+srv://admin:yXXEeI8bJDIJBLCL@cluster0.adwjbav.mongodb.net/streamix?retryWrites=true&w=majority&appName=Cluster0

server:
  port: 8082

tmdb:
  api:
    key: f33c417070653dbf2c8fd8fd63e6e998
    base-url: https://api.themoviedb.org/3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
