spring:
  application:
    name: catalog-service
  mongodb:
    uri: ${MONGODB_URI}

server:
  port: 8082

tmdb:
  api:
    key: ${TMDB_API_KEY}
    base-url: https://api.themoviedb.org/3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
